# Generated by Django 5.1.7 on 2026-03-11 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregatedJobRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=100)),
                ("source_job_id", models.CharField(blank=True, max_length=255)),
                ("apply_url", models.URLField(max_length=500)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("posted_date", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("is_live", models.BooleanField(db_index=True, default=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregated_record",
                        to="core.job",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "source_job_id"],
                        name="core_aggreg_source_05b10f_idx",
                    ),
                    models.Index(
                        fields=["source", "is_live"],
                        name="core_aggreg_source_69bdf8_idx",
                    ),
                ],
                "unique_together": {("source", "source_job_id")},
            },
        ),
    ]
