# Generated by Django 5.1.7 on 2026-03-12 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_aggregatedjobrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="aggregatedjobrecord",
            name="chat_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aggregatedjobrecord",
            name="partner_company_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="aggregatedjobrecord",
            name="partner_contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="aggregatedjobrecord",
            name="partner_employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_aggregated_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
