# Generated by Django 5.1.7 on 2026-02-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_jobapplicantsmessage'),
        ('core', '0005_jobapplicantsmessage'),
    ]

    operations = [
    ]
