# Generated by Django 5.1.7 on 2026-02-21 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260221_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicantsmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicantsmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_room_recipient_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplicantsmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_room_replies', to='core.jobapplicantsmessage'),
        ),
    ]
