"""
Django settings for joblink project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from django.contrib.messages import constants as messages
from dotenv import load_dotenv
import dj_database_url
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [
    "www.stepper.dpdns.org",
    "stepper.dpdns.org",
    ".onrender.com",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'cloudinary',
    'cloudinary_storage',
    'channels',
    'widget_tweaks',
    'django.contrib.humanize',
    'core.apps.CoreConfig',
    'anymail',
]

INSTALLED_APPS += ["django_celery_results"]

CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

CELERY_RESULT_BACKEND = "django-db"

# -----------------------------------------------
# CLOUDINARY / MEDIA FILE CONFIGURATION
# -----------------------------------------------

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv("CLOUDINARY_CLOUD_NAME"),
    'API_KEY': os.getenv("CLOUDINARY_API_KEY"),
    'API_SECRET': os.getenv("CLOUDINARY_API_SECRET"),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # Messages MUST come immediately after sessions
    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # Custom middleware that uses messages MUST come AFTER MessageMiddleware
    'core.middleware.employer_verification.EmployerVerificationMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]


ROOT_URLCONF = 'joblink.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # ⭐ CUSTOM JOBLINK PROCESSORS
                'core.context_processors.employer_badge',
            ],
        },
    },
]


# WSGI & ASGI
WSGI_APPLICATION = 'joblink.wsgi.application'
ASGI_APPLICATION = 'joblink.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
    #'default': {
       # 'ENGINE': 'django.db.backends.sqlite3',
       # 'NAME': BASE_DIR / 'db.sqlite3',
   #}
#}

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True)
}
#DATABASE_URL = os.environ.get('DATABASE_URL')
#if DATABASE_URL:
    #DATABASES['default'] = dj_database_url.parse(DATABASE_URL, conn_max_age=600)

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True

# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Custom user model
AUTH_USER_MODEL = 'core.CustomUser'  # Make sure 'core' is your user model app name


# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Optional: for collectstatic (production)
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticfilesStorage'

# Media files (e.g. uploaded CVs)
#MEDIA_URL = '/media/'
#MEDIA_ROOT = BASE_DIR / 'media'
LOGIN_URL = '/login/' 
LOGOUT_REDIRECT_URL = '/logout-success/'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

#if not DEBUG:
    #WHITENOISE_MANIFEST_STRICT = False
    #WHITENOISE_ADD_HEADERS_FUNCTION = lambda *args, **kwargs: None
    # This will tell whitenoise to also serve media:
    #STATICFILES_DIRS += [MEDIA_ROOT]

MESSAGE_TAGS = {
    messages.SUCCESS: 'success',
    messages.ERROR: 'danger',
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OTP_EXPIRY_MINUTES = 5
OTP_RESEND_COOLDOWN = 60        # seconds
OTP_MAX_ATTEMPTS = 5
TRUSTED_DEVICE_DAYS = 30

# Security / Domain
SITE_ID = 1
SITE_URL = "https://www.stepper.dpdns.org"

SITE_NAME = "Joblink Kenya"
SITE_DOMAIN = "https://www.stepper.dpdns.org"

APPLE_CLIENT_ID = os.getenv("APPLE_CLIENT_ID", "")
APPLE_REDIRECT_URI = os.getenv("APPLE_REDIRECT_URI", f"{SITE_URL}/auth/apple/callback/")
MICROSOFT_CLIENT_ID = os.getenv("MICROSOFT_CLIENT_ID", "")
MICROSOFT_CLIENT_SECRET = os.getenv("MICROSOFT_CLIENT_SECRET", "")
MICROSOFT_REDIRECT_URI = os.getenv(
    "MICROSOFT_REDIRECT_URI",
    f"{SITE_URL}/auth/microsoft/callback/",
)

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# HTTP Strict Transport Security (HSTS)
SECURE_HSTS_SECONDS = 3600  # Adjust as needed
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Prevent content sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# If behind a proxy (like Render), tell Django to trust X-Forwarded-Proto
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = True


# Cross-site scripting protection
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "DENY"

EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"

BREVO_API_KEY = os.getenv("BREVO_API_KEY")
TEXTBELT_API_KEY = os.getenv("TEXTBELT_API_KEY", "textbelt")

# Default sender
DEFAULT_FROM_EMAIL = "Joblink Kenya <support@stepper.dpdns.org>"

WHAPI_TOKEN = os.getenv("WHAPI_TOKEN")

STRIPE_PUBLIC_KEY = os.getenv('STRIPE_PUBLIC_KEY', 'pk_test_51RvRvyIw0VfmVsTbChuKMjJburhqmWL65VM1qxZ3Az5RYEhMETg5kGZaXH91aK8gosui5RPb7Trr04nus1tE67tD00lBPljhkb')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'sk_test_51RvRvyIw0VfmVsTbawUSdB6xKh4RSPtlt4TqLzgNV7u1sWa09mr3XLruD5rq1FinGBmL9XLodixb27p1J3eS3IAz00OfwBFe4V')

CSRF_TRUSTED_ORIGINS = [
    "https://www.fazul.dpdns.org",
    "https://fazul.dpdns.org",
    "https://www.stepper.dpdns.org",
    "https://stepper.dpdns.org",
    "https://joblink-kenya-6flx.onrender.com",
]


# Channels layers
if os.getenv("REDIS_URL"):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [os.getenv("REDIS_URL")]},
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }

# Channels & chat defaults
CHAT_MAX_MESSAGE_LENGTH = 2000
