name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Inject Secrets to .env
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "DEBUG=False" >> .env

      # Generate fresh migration files (based on your models)
      - name: Reset migrations and remake them fresh
        run: |
          find . -path "*/migrations/*.pyc" -delete
          find . -path "*/migrations/[0-9]*.py" -delete
          python manage.py makemigrations

      # Tell Django to reset its migration history for your core app
      - name: Fake zero migration state (to avoid 'table does not exist' errors)
        run: |
          python manage.py migrate core zero --fake-initial

      # Apply migrations normally
      - name: Run database migrations
        run: python manage.py migrate

      - name: Collect static
        run: python manage.py collectstatic --noinput
