name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt

      # Run migrations against your Render DB:
      - name: Run Django Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python manage.py migrate --noinput

      # trigger Render
      - name: Deploy to Render
        uses: render-examples/deploy-to-render@v1
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
